{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "background_save": true,
          "base_uri": "https://localhost:8080/"
        },
        "id": "-7j6wi_1_Gfu",
        "outputId": "97783740-321a-4d12-c4d5-2bd48a43cb8a"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Loading California Housing data...\n",
            "Training RandomForestRegressor (n_estimators=100)...\n",
            "\n",
            "[1/3] Waterfall plot — observation 0 (high-value home)...\n",
            "Saved: figures/shap_waterfall_demo.png\n",
            "[2/3] Beeswarm plot — global importance...\n",
            "Saved: figures/shap_beeswarm_demo.png\n",
            "[3/3] MDI vs SHAP comparison...\n",
            "Saved: figures/compare_importance_demo.png\n",
            "\n",
            "Importance ranking (sorted by SHAP):\n",
            "               MDI    SHAP\n",
            "MedInc      0.5249  0.3809\n",
            "Latitude    0.0889  0.1806\n",
            "AveOccup    0.1384  0.1644\n",
            "Longitude   0.0886  0.1469\n",
            "HouseAge    0.0546  0.0580\n",
            "AveRooms    0.0443  0.0364\n",
            "AveBedrms   0.0296  0.0194\n",
            "Population  0.0306  0.0135\n",
            "\n",
            "✅ shap_utils.py demo complete. Check figures/ directory.\n"
          ]
        }
      ],
      "source": [
        "\"\"\"\n",
        "shap_utils.py\n",
        "=============\n",
        "Reusable SHAP utility module for Lab 19 — Tree-Based Models & Random Forests\n",
        "ECON 5200: Causal Machine Learning & Applied Analytics\n",
        "\n",
        "Provides three functions:\n",
        "    - explain_prediction()  : SHAP waterfall plot for a single observation\n",
        "    - global_importance()   : SHAP beeswarm plot over the full dataset\n",
        "    - compare_importance()  : Side-by-side MDI vs SHAP ranking bar chart\n",
        "\n",
        "All functions use shap.TreeExplainer, which is exact and fast for tree ensembles.\n",
        "For non-tree models, swap in shap.KernelExplainer (slower, approximate).\n",
        "\"\"\"\n",
        "\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.gridspec as gridspec\n",
        "import shap\n",
        "from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor\n",
        "from sklearn.inspection import permutation_importance\n",
        "from typing import Union\n",
        "\n",
        "# Type alias for supported sklearn tree ensemble models\n",
        "TreeModel = Union[RandomForestRegressor, GradientBoostingRegressor]\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Private helper: build or reuse a TreeExplainer + shap_values\n",
        "# ---------------------------------------------------------------------------\n",
        "def _get_shap_values(\n",
        "    model: TreeModel,\n",
        "    X: pd.DataFrame,\n",
        ") -> tuple:\n",
        "    \"\"\"\n",
        "    Build a shap.TreeExplainer and compute SHAP values.\n",
        "\n",
        "    TreeExplainer uses the exact TreeSHAP algorithm — it exploits the\n",
        "    tree structure to compute exact Shapley values in polynomial time,\n",
        "    unlike KernelExplainer which is model-agnostic but uses Monte Carlo\n",
        "    sampling and can be 100x slower.\n",
        "\n",
        "    Parameters\n",
        "    ----------\n",
        "    model : fitted sklearn tree ensemble\n",
        "    X     : feature matrix (DataFrame preserves feature names)\n",
        "\n",
        "    Returns\n",
        "    -------\n",
        "    explainer   : shap.TreeExplainer\n",
        "    shap_values : np.ndarray of shape (n_samples, n_features)\n",
        "    \"\"\"\n",
        "    # check_additivity=False avoids a slow consistency check in some RF versions\n",
        "    explainer = shap.TreeExplainer(model)\n",
        "    shap_values = explainer.shap_values(X, check_additivity=False)\n",
        "    return explainer, shap_values\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# 1. explain_prediction\n",
        "# ---------------------------------------------------------------------------\n",
        "def explain_prediction(\n",
        "    model: TreeModel,\n",
        "    X: pd.DataFrame,\n",
        "    idx: int,\n",
        "    title_suffix: str = \"\",\n",
        "    save_path: str | None = None,\n",
        ") -> None:\n",
        "    \"\"\"\n",
        "    Generate a SHAP waterfall plot explaining a single prediction.\n",
        "\n",
        "    A waterfall plot starts from the model's expected output (E[f(x)]),\n",
        "    then shows each feature's additive contribution — positive (red) or\n",
        "    negative (blue) — to arrive at f(x) for this observation.\n",
        "\n",
        "    SHAP values are additive by the Shapley property: the sum of all\n",
        "    SHAP values plus the base value exactly equals the model's output.\n",
        "    This additivity comes from cooperative game theory — each feature\n",
        "    receives its \"fair share\" of the prediction gap from the baseline.\n",
        "\n",
        "    Parameters\n",
        "    ----------\n",
        "    model       : fitted sklearn tree ensemble (RandomForest or GBR)\n",
        "    X           : feature matrix as a DataFrame (test or full set)\n",
        "    idx         : integer row index of the observation to explain\n",
        "    title_suffix: optional string appended to the plot title\n",
        "    save_path   : if provided, saves the figure to this path (.png)\n",
        "\n",
        "    Returns\n",
        "    -------\n",
        "    None  (displays or saves a matplotlib figure)\n",
        "\n",
        "    Example\n",
        "    -------\n",
        "    >>> explain_prediction(best_rf, X_test, idx=0, title_suffix=\"High-value home\")\n",
        "    \"\"\"\n",
        "    if idx < 0 or idx >= len(X):\n",
        "        raise IndexError(\n",
        "            f\"idx={idx} is out of bounds for X with {len(X)} rows.\"\n",
        "        )\n",
        "\n",
        "    explainer, shap_values = _get_shap_values(model, X)\n",
        "\n",
        "    shap_explanation = shap.Explanation(\n",
        "        values=shap_values[idx],\n",
        "        base_values=explainer.expected_value,\n",
        "        data=X.iloc[idx].values,\n",
        "        feature_names=list(X.columns),\n",
        "    )\n",
        "\n",
        "    title = f\"SHAP Waterfall — Observation {idx}\"\n",
        "    if title_suffix:\n",
        "        title += f\" ({title_suffix})\"\n",
        "\n",
        "    plt.figure(figsize=(9, 5))\n",
        "    shap.plots.waterfall(shap_explanation, show=False)\n",
        "    plt.title(title, fontsize=12, pad=10)\n",
        "    plt.tight_layout()\n",
        "\n",
        "    if save_path:\n",
        "        plt.savefig(save_path, dpi=150, bbox_inches=\"tight\")\n",
        "        print(f\"Saved: {save_path}\")\n",
        "    else:\n",
        "        plt.show()\n",
        "    plt.close()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# 2. global_importance\n",
        "# ---------------------------------------------------------------------------\n",
        "def global_importance(\n",
        "    model: TreeModel,\n",
        "    X: pd.DataFrame,\n",
        "    max_display: int = 10,\n",
        "    save_path: str | None = None,\n",
        ") -> None:\n",
        "    \"\"\"\n",
        "    Generate a SHAP beeswarm plot showing global feature importance.\n",
        "\n",
        "    Each dot is one observation. The x-axis is the SHAP value (impact on\n",
        "    prediction). Color encodes the raw feature value (red = high, blue = low).\n",
        "    Features are sorted by mean |SHAP value|, giving a magnitude-ranked\n",
        "    global importance without the cardinality bias of MDI.\n",
        "\n",
        "    Parameters\n",
        "    ----------\n",
        "    model       : fitted sklearn tree ensemble\n",
        "    X           : feature matrix as a DataFrame\n",
        "    max_display : number of top features to display (default 10)\n",
        "    save_path   : if provided, saves the figure to this path (.png)\n",
        "\n",
        "    Returns\n",
        "    -------\n",
        "    None  (displays or saves a matplotlib figure)\n",
        "\n",
        "    Example\n",
        "    -------\n",
        "    >>> global_importance(best_rf, X_test, max_display=8)\n",
        "    \"\"\"\n",
        "    explainer, shap_values = _get_shap_values(model, X)\n",
        "\n",
        "    shap_explanation = shap.Explanation(\n",
        "        values=shap_values,\n",
        "        base_values=explainer.expected_value,\n",
        "        data=X.values,\n",
        "        feature_names=list(X.columns),\n",
        "    )\n",
        "\n",
        "    plt.figure(figsize=(9, 6))\n",
        "    shap.plots.beeswarm(shap_explanation, max_display=max_display, show=False)\n",
        "    plt.title(\"SHAP Beeswarm — Global Feature Importance\", fontsize=12, pad=10)\n",
        "    plt.tight_layout()\n",
        "\n",
        "    if save_path:\n",
        "        plt.savefig(save_path, dpi=150, bbox_inches=\"tight\")\n",
        "        print(f\"Saved: {save_path}\")\n",
        "    else:\n",
        "        plt.show()\n",
        "    plt.close()\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# 3. compare_importance\n",
        "# ---------------------------------------------------------------------------\n",
        "def compare_importance(\n",
        "    model: TreeModel,\n",
        "    X: pd.DataFrame,\n",
        "    y: pd.Series | np.ndarray,\n",
        "    n_repeats: int = 10,\n",
        "    random_state: int = 42,\n",
        "    save_path: str | None = None,\n",
        ") -> pd.DataFrame:\n",
        "    \"\"\"\n",
        "    Generate a side-by-side bar chart comparing MDI vs SHAP feature rankings.\n",
        "\n",
        "    MDI (Mean Decrease in Impurity) is fast but biased toward high-cardinality\n",
        "    features — continuous variables have more split opportunities, so they\n",
        "    accumulate impurity reduction by chance.\n",
        "\n",
        "    SHAP importance (mean |SHAP value|) is unbiased: it measures each feature's\n",
        "    actual contribution to predictions on held-out observations, using the\n",
        "    additive Shapley decomposition.\n",
        "\n",
        "    Parameters\n",
        "    ----------\n",
        "    model        : fitted sklearn RandomForestRegressor (must have\n",
        "                   feature_importances_ attribute; GBR also supported)\n",
        "    X            : feature matrix as a DataFrame (ideally the test set)\n",
        "    y            : target vector aligned with X\n",
        "    n_repeats    : permutation importance repetitions (default 10)\n",
        "    random_state : RNG seed for permutation importance\n",
        "    save_path    : if provided, saves the figure to this path (.png)\n",
        "\n",
        "    Returns\n",
        "    -------\n",
        "    importance_df : pd.DataFrame with columns [MDI, SHAP] sorted by SHAP rank\n",
        "\n",
        "    Example\n",
        "    -------\n",
        "    >>> df = compare_importance(best_rf, X_test, y_test, save_path=\"figures/compare.png\")\n",
        "    >>> print(df)\n",
        "    \"\"\"\n",
        "    feature_names = list(X.columns)\n",
        "\n",
        "    # --- MDI (built-in to the model) ---\n",
        "    if not hasattr(model, \"feature_importances_\"):\n",
        "        raise AttributeError(\n",
        "            \"Model does not have feature_importances_. \"\n",
        "            \"Use a tree-based ensemble (RandomForest, GBR).\"\n",
        "        )\n",
        "    mdi = pd.Series(model.feature_importances_, index=feature_names)\n",
        "\n",
        "    # --- SHAP mean |value| ---\n",
        "    _, shap_values = _get_shap_values(model, X)\n",
        "    shap_mean = pd.Series(\n",
        "        np.abs(shap_values).mean(axis=0), index=feature_names\n",
        "    )\n",
        "    # Normalize to [0,1] for fair visual comparison\n",
        "    shap_mean_norm = shap_mean / shap_mean.sum()\n",
        "\n",
        "    # --- Build comparison DataFrame, sort by SHAP ---\n",
        "    importance_df = pd.DataFrame(\n",
        "        {\"MDI\": mdi, \"SHAP\": shap_mean_norm}\n",
        "    ).sort_values(\"SHAP\", ascending=True)  # ascending for horizontal bar\n",
        "\n",
        "    # --- Plot ---\n",
        "    fig, axes = plt.subplots(1, 2, figsize=(12, 5), sharey=True)\n",
        "    colors = {\"MDI\": \"#4C72B0\", \"SHAP\": \"#DD8452\"}\n",
        "\n",
        "    for ax, col in zip(axes, [\"MDI\", \"SHAP\"]):\n",
        "        bars = ax.barh(\n",
        "            importance_df.index,\n",
        "            importance_df[col],\n",
        "            color=colors[col],\n",
        "            edgecolor=\"white\",\n",
        "            linewidth=0.5,\n",
        "        )\n",
        "        ax.set_title(\n",
        "            f\"{'MDI (Mean Decrease Impurity)' if col == 'MDI' else 'SHAP (mean |value|)'}\",\n",
        "            fontsize=11,\n",
        "        )\n",
        "        ax.set_xlabel(\"Normalized Importance\", fontsize=9)\n",
        "        ax.spines[[\"top\", \"right\"]].set_visible(False)\n",
        "        # Annotate values\n",
        "        for bar, val in zip(bars, importance_df[col]):\n",
        "            ax.text(\n",
        "                val + 0.002, bar.get_y() + bar.get_height() / 2,\n",
        "                f\"{val:.3f}\", va=\"center\", fontsize=8,\n",
        "            )\n",
        "\n",
        "    fig.suptitle(\n",
        "        \"MDI vs SHAP Feature Importance\\n\"\n",
        "        \"(MDI is biased toward high-cardinality features; SHAP is unbiased)\",\n",
        "        fontsize=12, y=1.02,\n",
        "    )\n",
        "    plt.tight_layout()\n",
        "\n",
        "    if save_path:\n",
        "        plt.savefig(save_path, dpi=150, bbox_inches=\"tight\")\n",
        "        print(f\"Saved: {save_path}\")\n",
        "    else:\n",
        "        plt.show()\n",
        "    plt.close()\n",
        "\n",
        "    return importance_df.sort_values(\"SHAP\", ascending=False)\n",
        "\n",
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# __main__ demo — run with: python src/shap_utils.py\n",
        "# ---------------------------------------------------------------------------\n",
        "if __name__ == \"__main__\":\n",
        "    \"\"\"\n",
        "    Demonstration block: trains a small RF on California Housing and\n",
        "    exercises all three functions. Run from repo root:\n",
        "        python src/shap_utils.py\n",
        "    \"\"\"\n",
        "    from sklearn.datasets import fetch_california_housing\n",
        "    from sklearn.model_selection import train_test_split\n",
        "    import os\n",
        "\n",
        "    print(\"Loading California Housing data...\")\n",
        "    data = fetch_california_housing()\n",
        "    X = pd.DataFrame(data.data, columns=data.feature_names)\n",
        "    y = data.target\n",
        "    X_train, X_test, y_train, y_test = train_test_split(\n",
        "        X, y, test_size=0.2, random_state=42\n",
        "    )\n",
        "\n",
        "    print(\"Training RandomForestRegressor (n_estimators=100)...\")\n",
        "    model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)\n",
        "    model.fit(X_train, y_train)\n",
        "\n",
        "    os.makedirs(\"figures\", exist_ok=True)\n",
        "\n",
        "    print(\"\\n[1/3] Waterfall plot — observation 0 (high-value home)...\")\n",
        "    explain_prediction(\n",
        "        model, X_test, idx=0,\n",
        "        title_suffix=\"demo\",\n",
        "        save_path=\"figures/shap_waterfall_demo.png\",\n",
        "    )\n",
        "\n",
        "    print(\"[2/3] Beeswarm plot — global importance...\")\n",
        "    global_importance(\n",
        "        model, X_test,\n",
        "        save_path=\"figures/shap_beeswarm_demo.png\",\n",
        "    )\n",
        "\n",
        "    print(\"[3/3] MDI vs SHAP comparison...\")\n",
        "    df = compare_importance(\n",
        "        model, X_test, y_test,\n",
        "        save_path=\"figures/compare_importance_demo.png\",\n",
        "    )\n",
        "    print(\"\\nImportance ranking (sorted by SHAP):\")\n",
        "    print(df.round(4).to_string())\n",
        "\n",
        "    print(\"\\n✅ shap_utils.py demo complete. Check figures/ directory.\")"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
